### ISSUE TITLE
The compiled kernel fails to boot

### ISSUE THREAD

**Issue by ghost** [M2Team/MinCLR#1]
When I use [kernel-config-vmware](https://github.com/M2Team/MinCLR/raw/main/Platform/Linux/kernel-config-vmware-x64) to compile the Linux Kernel, I find that the compiled kernel cannot boot the OS successfully.

The linux kernel which I use is the latest development version downloaded from [GitHub](https://github.com/torvalds/linux)。

I compiled the Kernel with [Ubuntu 22.04 Daily Build](https://cdimage.ubuntu.com/daily-live/current/) Operating System, also tested under it.

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/18372244/153829752-d3a51525-fdab-47bf-bc62-fe85333f6517.png)

**Comment by MouriNaruto** [comment]
I think it may be the issue from the development branch of the kernel.

You should use Linux Kernel 5.15.x with the kernel config. (I have only adapted the latest LTS kernel (5.15.x for example) at present.)

I will upgrade to the new kernel when the next LTS kernel comes out.

Kenji Mouri
